### ISSUE TITLE
Get Fest 10 graphics.

### ISSUE THREAD

**Issue by jjok** [mcflynnthm/com.johnrflynn.thefest10#4]
Replace Fest 9 temp images with Fest 10 ones.

**Comment by jjok** [comment]
mcflynnthm, did you create the Fest 9 graphics yourself, or did someone send you them, already done?

**Comment by mcflynnthm** [comment]
I created the logo one myself, from the larger Fest 9 image. Peej emailed me the logo for Fest 10, though I'd been hoping for just the word "Fest" and the number portion. I'm gonna see what I can do to make it a reasonable size, height-wise, tonight.

**Comment by mcflynnthm** [comment]
Hokay, I added a smaller version of the Fest 10 logo. I'm gonna keep tinkering with it, though.
