### ISSUE TITLE
Layout issues.

### ISSUE THREAD

**Issue by jjok** [mcflynnthm/com.johnrflynn.thefest10#5]
On band detail screen, the Shows block overlaps with the Band Bio section, so you can't read the bottom of the bio.
This may just be on low-res devices.

Environment: HTC Wildfire, resolution: 240 x 320

**Comment by jjok** [comment]
This issue is even worse when the device is in landscape mode, as you only get about 20px for the Band Bio section.
It's because the Picture and Shows sections have fixed heights.

I would suggest either:
- having the picture and bio in one scrollable section and the Shows still fixed, or
- having none of the sections fixed, and all of it in one scrollable section.

Also, I think it would be good to not have the default image. If no band image is available, just don't show any image. This would save screen space. I don't know if you're already planning on doing that.

**Comment by mcflynnthm** [comment]
I was planning to just not allow landscape, actually; I can't see a situation wherein this application benefits from being used like that.

It might have been in another version, but that band bio should be a ScrollView. Throwing the picture in that View shouldn't be a problem. The shows should definitely stay fixed, though.
I'd like to keep the image/default image, though hopefully this year there won't be as much need for the default. Seems that way so far, anyway.

**Comment by jjok** [comment]
Cool.
How would the shows work if there are several shows for one band? Will it also scroll?

**Comment by mcflynnthm** [comment]
There are a couple of bands that have a few shows in the current data, actually. Tiltwheel, I believe, has two shows, so there's an example of how it'll work.
If you see the other issue I created about shows on that page needing to be a TableView, that would take care of scrolling, though the current implementation as a GridView does that too; both Views have a ScrollView "built-in."

**Comment by jjok** [comment]
Ok. I meant, what would happen if there were more shows that could it into the height of the white box, but maybe that will be more than any band will be doing?
