### ISSUE TITLE
Shows a appear on the wrong day.

### ISSUE THREAD

**Issue by jjok** [mcflynnthm/com.johnrflynn.thefest10#6]
On the By Date screen, shows which are after midnight appear on the screen of the morning of the day they actually happen.
I think it would be much more helpful if they appeared on the screen of the night before.

**Comment by mcflynnthm** [comment]
Yeah, I forgot to add that to my to-do list. I'm working on using the Java Date class instead of a simple String for the date, which should make it easier to put the late-night shows where they logically should be.
